name: MoveBem
description: A minimal Flutter app with a MoveBem splash/loading screen.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  crypto: ^3.0.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9   # ✅ ADICIONADO

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon.png
    - assets/rotina1.png
    - assets/rotina2.png
    - assets/rotina3.png
    - assets/agua.png
    - assets/AM_1.png
    - assets/AM_2.png
    - assets/AM_3.png
    - assets/AM_4.png
    - assets/AM_5.png
    - assets/AM_6.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  remove_alpha_ios: true
